server.port: ${PORT:8662}

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    employee-crud-service:
      path: /employee-resource/**
      serviceId: employee-crud-service
      stripPrefix: true
    employee-service:
      path: /employee-service/**
      serviceId: employee-service
      stripPrefix: true

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    non-secure-port: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8661}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'